---
# vars.yml
#
# Shows the value of all variables/facts.
#
# Example:
#
#   ansible-playbook vars.yml -e 'hosts=localhost'
#
- hosts: all
 
  tasks:
    - debug: var=vars
    - debug: var=hostvars[192.168.0.120]
