---
- hosts: all
  connection: network_cli

  vars:
    cli:
      ansible_connection: network_cli
      ansible_network_os: ios
      ansible_user: admin
      ansible_password: admin
      ansible_become: yes
      ansible_become_method: enable
      ansible_become_password: admin

  tasks:

  - name: Gather facts
    ios_facts:
      provider: ""
    register: result

  - debug: var=result 
