---
- name: RUN COMMAND AND PRINT TO TERMINAL WINDOW
  hosts: all
  gather_facts: false

  tasks:

    - name: RUN ARISTA COMMAND
      cli_command:
        command: show ip interface brief
      register: command_output

    - name: PRINT TO TERMINAL WINDOW
      debug:
        msg: "{{command_output.stdout}}"
