---
- hosts: all
  connection: local

  vars:
    cli:
      username: admin
      password: admin
      authorize: yes

  tasks:

  - name: Gather facts
    ios_facts:
      provider: ""
    register: result

  - debug: var=result 
