---
- hosts: all
  connection: network_cli

  vars:
    cli:
      username: admin
      password: admin
      authorize: yes
      auth_pass: cisco

  tasks:

  - name: Gather facts
    ios_facts:
      provider: ""
    register: result

  - debug: var=result 
