---

- name: SHOW VERSION
  hosts: all
  gather_facts: true
  connection: network_cli
  
  - debug:
    msg: System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}

  - debug:
    msg: System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}
  when: ansible_default_ipv4.gateway is defined

# Example that prints return information from the previous task
- shell: /usr/bin/uptime
  register: result

- debug:
    var: result
    verbosity: 2

- name: Display all variables/facts known for a host
  debug:
    var: hostvars[inventory_hostname]
    verbosity: 4

  tasks:
    - name: run the command 'show version'
      ios_command:
        commands: show version
